name: Publish Github Page
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build site
        uses: docker://pandoc/core:2.9
        with:
          entrypoint: "ls /github/workspace/"
