name: Publish Github Page
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/core:2.9
      options: "--entrypoint /bin/bash"
    steps:
      - uses: actions/checkout@v2
      - name: Build site
        run: build.sh
